### ISSUE TITLE
セキュリティポリシー

### ISSUE THREAD

**Issue by Rintan** [GenbuProject/GPlusTheme-for-Mastodon#1]
同様の問題が別のインスタンスでも発生することが確認されました。対処法のドキュメントへの追記をお願いします。
[https://github.com/accelforce/odakyudon/commit/56025767666864ba20eb848c4fef26094b8e73d4#diff-f9478788f0659efb94cf87ef033f1792](url)

**Comment by GenbuHase** [comment]
申し訳ございません。ドキュメントの追記、しておきます。(書くの忘れてた)
ありがとうございましたm(_ _)m
